### ISSUE TITLE
Reuse pieces of ASM from boost.context

### ISSUE THREAD

**Issue by target-san** [zonyitoo/context-rs#10]
Since these sub-issues are tightly coupled for me, I'm gonna post them here
1. Reuse ASM code from boost.context - this is a tested and proven ASM for coroutine manipulation. We can greatly benefit from it
2. Due to (1), store context state on top of stack, without heap allocations
3. Do not place coroutine specific data on heap and place it 'below' stack to reduce amount of allocations. This will allow to drop FnBox and go stable.
4. Use prebuilt pieces of ASM and just link them - this will allow to drop asm feature and go stable

I'd like to discuss these changes, whether they're acceptable and needed at all. I also plan to make demo refactoring in my fork in 2-3 days.

For reference on what I plan to do please see:
https://github.com/target-san/tasklets
https://github.com/target-san/boost.context

Thanks

**Comment by zonyitoo** [comment]
This crate does not need `FnBox`. `FnBox` is used in `coio-rs` or other coroutine implementation to support passing a closure as the callback function of coroutine.

It would be better if this change could compile without depending on the external `boost` libraries.

The ASM in this crate is borrowed from the `libgreen` of version `0.12-dev` standard library. I have only tested the code for `x86_64` platform on my laptop. AppVeyor indicates that it cannot be compiled on Windows. So I hope to refactor this with ASM of `boost.context` will help this crate to support all platforms, truly.

The registers are actually store in the instance of `Context`, https://github.com/zonyitoo/context-rs/blob/master/src/context.rs#L25.

**Comment by target-san** [comment]
Our code differs too much as I see now. I'll try to finish something comparable in my micro crate, and then we can think on merging our approaches into one.
As for boost, we actually need only asm code from there and nothing more. And you gave me a good idea to try appveyor to compile those pieces of asm for multiple platforms.

The only showstopper I encountered is a reliable freeing of coroutine's underlying stack. Context jumper requires some stack, even if current state isn't stored - because arguments are passed on stack for some architectures. So stack needs to be freed after final jump. Or I just want too much.

**Comment by zonyitoo** [comment]
Please check this out: `https://github.com/zonyitoo/context-rs/blob/master/src/stack.rs`. The stack is allocated via `mmap` and it will be freed when the instance of `Context` is deallocating.

**Comment by target-san** [comment]
It seems I'm trying to solve a problem which is too generic, as I'm allowing "death jumps" to arbitrary context. Maybe I'd just make that final jump lead to top context, and jump func taking Context by &mut. And I'll need stable catch_panic for proper premature termination.

Now I understand why many people vote for stackless coroutines - they're just order of magnitude easier to manage, when proper code transformer is available.

**Comment by zonyitoo** [comment]
I personally love stackless coroutines. :). But since it is not available right now, I have to remake the wheel.

**Comment by target-san** [comment]
Offtop:
You can try implement appropriate code transformer on unstable :smile: Like

``` rust
    #[async] pub fn foo(arg: i32) -> i32 {
        await somefuture;
    }
```

To me this looks like trade off - stackful are harder to manage, but easier to use and and of medium difficulty to implement. And stackless are easy to manage, but medium to use and hard to implement.

**Comment by zonyitoo** [comment]
Yes it is. I am focus on this RFC: https://github.com/rust-lang/rfcs/issues/388. But since it is still an RFC, we should just make coroutine available right now.

**Comment by zonyitoo** [comment]
Ping.. What is your progress?

**Comment by target-san** [comment]
Not too much unfortunately. I currently need to decide how to place service data under the stack: pointer to restore from, reference to parent context, stack deallocator. 
As for now, I decided to organize contexts in a top-down "stack", so I can ensure that they're properly destroyed.
Or I can try to drop all this crap and play with your version of context switching.
Unfortunately I don't have enough spare time lately.

**Comment by zonyitoo** [comment]
Hmm, just take your time. :)

**Comment by target-san** [comment]
Here are some thoughts.
1. Your current lowlevel approach seems to be more flexible - it's not tied to the location where context state will be stored.
2. As I understand, you currently store context state on a separate heap piece, and coroutine function also occupies separate space on the heap. That's the reason of using FnBox
3. You have code related to stack bounds store, which is the reason of using asm!()

And here are some of my ideas which will allow me to provide you real help instead of fairy tales of some awesome solution when I'll finish. As I'll be able to work iteratively.
1. Check if it's possible to pack service structures directly onto the stack. This will allow context data along with coroutine, and get rid of FnBox
2. Try to provide some ASM pieces precompiled, so there will be no need for separate assembler.
3. Merge stack bounds records with context-switching ASM code. This will allow to get rid of asm!() unsafe feature.
4. The structure of registers storage seems to be of interest only to lowlevel ASM pieces. So it might be possible to simply store that size in ASM code as constant, and then get rid of any Registers struct traces from Rust code. Though I'm not sure yet.

I also think that this discussion issue has lived to its end and can be closed.

**Comment by zonyitoo** [comment]
1. Another problem to be solved by using `FnBox` is to support closures. My solution is to allocate the closure on the heap so that I can use send it through a pointer to the coroutine initialization function.
2. This is good.
3. Actually I hope to merge the ASM code into the `asm!()` so that we won't need the 2. . I have tried one day to migrate those code into `asm!()`, but failed because of some weird bugs.
4. It is possible, just store it on the top of the stack. When the memory of the stack is allocated, advance the pointer with the size of the struct `Registers`.

I will close this, you may open another issue.
