### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by dpc** [zonyitoo/context-rs#11]
Hi,

Any change for a new version on crates.io. I depend on the #6 , and I'd like to push mioco 0.2 sometime this weekend.

Thanks!

**Comment by zonyitoo** [comment]
It can't be... `simd` is on github.
I want to publish it, too!!

**Comment by zonyitoo** [comment]
The latest version have removed dependency of `simd`, it is ready to be published to crates.io.

But it is still failed to compile on windows...

**Comment by dpc** [comment]
I personally care very very little about Windows. :)

**Comment by zonyitoo** [comment]
I have already publish `v0.1.3`.
