### ISSUE TITLE
Add `Context::load(&self) -> !`

### ISSUE THREAD

**Issue by dpc** [zonyitoo/context-rs#2]
In places like this https://github.com/zonyitoo/context-rs/blob/master/src/context.rs#L386 it would be nice to not have to use dummy context. Is optimizer smart enough to eliminate the unnecessary store anyway?

**Comment by zonyitoo** [comment]
I don't think the optimizer could eliminate the `dummy`.

The `Context::load` will work just like `goto` and you have to make sure that it will never come back. It will require to add a new function in `asm`. :)

**Comment by zonyitoo** [comment]
@dpc Please test this commit, I have only tested it on OS X with x86_64 CPU.

**Comment by dpc** [comment]
All right. Thanks! I might be slow with this one, as I'm ridiculously busy recently.

**Comment by dpc** [comment]
Works for me in https://github.com/dpc/mioco/tree/context-feature-load

**Comment by zonyitoo** [comment]
What's your CPU arch? x86_64?

**Comment by zonyitoo** [comment]
Merged

**Comment by dpc** [comment]
x86_64, yes. Hmmm... You just gave me an idea, that I could write a cross-compiling testing toolchain. A wrapper using Quemu to run foreign architecture test build...

**Comment by zonyitoo** [comment]
Excellent, please help me test this crate ;)
