### ISSUE TITLE
Segmentation fault on windows

### ISSUE THREAD

**Issue by canndrew** [zonyitoo/context-rs#20]
I'm trying to run `cargo test` on windows in cygwin. I'm using the GNU ABI version of rust nightly. And I'm getting a segfault.

gdb reckons:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 4560.0xc20]
rust_save_registers () at src\asm\x86_64/_context.S:189
189             mov %rax, (RUSTRT_IP*8)(RUSTRT_ARG0_S)
```

Any ideas?

**Comment by zonyitoo** [comment]
Hmm... I haven't tested it on windows actually, that's why I need #8

**Comment by canndrew** [comment]
Fixed it, sort of. Neither the `__MINGW32__` or `_WINDOWS` flags were `#define`d so the assembler wasn't using the windows code. Instead it thought `RUSTRT_ARG0_S` was `%rdi` and so was segfaulting. For a workaround I can add just `#define _WINDOWS 1` to the top of `regs.S` and `_context.S`.

**Comment by zonyitoo** [comment]
Ah!! What's your assembler actually?

**Comment by canndrew** [comment]
Not sure, looks like the output of `gcc::compile_library` is getting swallowed by cargo. I'd say it's just the GNU assembler that comes with gcc on cygwin though.

**Comment by zonyitoo** [comment]
It would be the gcc from mingw. Hmm, that's weird.

**Comment by canndrew** [comment]
If you need me to try anything just tell me.

**Comment by zonyitoo** [comment]
Have you tried to compile it with x86 compiler? It crashed under linux-x86, let's see whether it works under windows.

**Comment by canndrew** [comment]
Similar problem. It doesn't build unless I add `#define _WIN32`. Other than that though, all tests pass.

**Comment by zonyitoo** [comment]
Alright, thanks for your help. :) I am going to close this issue because problem is already solved.

**Comment by zonyitoo** [comment]
@canndrew You may want to try the latest commit, I added `defined(_WIN32)` as an alternative condition.

**Comment by canndrew** [comment]
Nah, that didn't help :/

**Comment by Tyde** [comment]
I do also get a segmentation fault, but I might have found my problem: My standard gcc was the one from cycgwin.
When I list the preprocessor defines of this gcc, there is no _WIN32 and no _WINDOWS. 

I don't know if cygwin should be supported, but if this should also work with cygwin, you also need a `#ifdef __CYGWIN__`

Anyways: Switching to Mingw fixed the problem

**Comment by zonyitoo** [comment]
Thanks @Tyde ! Right now we are working on porting `Boost.Context` into this crate, this problem may not exists in the new impl. But I will still keep my eyes on this `__CYGWIN__` macro.

@lhecker Please check whether the new ASM is compatible with cygwin.

**Comment by zonyitoo** [comment]
@Tyde and @canndrew you may want to try the latest commit in cygwin, thanks for your help.

**Comment by canndrew** [comment]
I just ran `cargo test` on master on cygwin. All tests passed :ok_hand:

**Comment by zonyitoo** [comment]
Excellent! But now context-rs 1.0 is going to release. You may be interested in trying that out in your computer. See the `1.0` branch. :)
