### ISSUE TITLE
Is `Stack` `Send`?

### ISSUE THREAD

**Issue by dpc** [zonyitoo/context-rs#32]
Seems to me that `Stack` should be send-able, but it isn't.

**Comment by zonyitoo** [comment]
Well, maybe it should be `Send`able. But in practical use, we won't actually *send* the `Stack` instance to another thread, right? The `Stack` maybe stored somewhere globally shared between threads.

**Comment by lhecker** [comment]
@zonyitoo We should probably still make it `Send` since the struct itself and all it's members are basically `const`.

**Comment by zonyitoo** [comment]
@dpc Please check the latest commit. I will publish it to crates.io if it is Ok.

**Comment by dpc** [comment]
Should the `Stack` be stored globally? I was actually planing to send it along the `Context` at all times.

**Comment by dpc** [comment]
The commit LGTM

**Comment by zonyitoo** [comment]
Published v1.0.1.

Well, `Stack` could be stored with the `Context`, but in our lib, `Stack` is stored on the stack memory that it represents.

**Comment by dpc** [comment]
BTW. Is there any point in trying to reuse stacks after `Context` using them is gone?

**Comment by zonyitoo** [comment]
Preventing pointless stack reallocation.
