### ISSUE TITLE
x86 support?

### ISSUE THREAD

**Issue by aji** [zonyitoo/context-rs#4]
My `uname -m` is `i686`, but `build.rs` doesn't select `i686` and fails. I have to add `cfg(target_arch = "x86")` to match my system.

**Comment by zonyitoo** [comment]
Ah, https://github.com/zonyitoo/context-rs/blob/master/build.rs#L12 uses `target_arch = "i686"` to build, you could try to change the `i686` to `x86` and test if it works on your system.

To be honest, I have only tested on `x86_64` platform.

**Comment by zonyitoo** [comment]
Ah wait, you said your `uname -m` is `i686` but `build.rs` doesn't select `i686`? Well, that is a Rust's problem ...

**Comment by aji** [comment]
I changed to `x86` and it does work. It seems Rust nightly chooses `x86` as the `target_arch` on `i686-unknown-linux-gnu`: https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/i686_unknown_linux_gnu.rs#L22

**Comment by aji** [comment]
The point is moot, though, because I cannot seem to get `simd` to build on my system via cargo. I think I've held on to my 32 bit system long enough.

**Comment by zonyitoo** [comment]
You could fork the `simd` to modify `i686` to `x86` and then try to build this crate. I am not sure the assembly code for x86 platform actually works ...

**Comment by zonyitoo** [comment]
This one could be merged to #8
